### ISSUE TITLE
Conclusão das Conexões da Lição 1

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#1]
As figuras não possuem descrição detalhada na parte de Conexões na primeira lição.

**Comment by franciscomattos** [comment]
Aqui seria melhor quem fez as figuras documentá-las. pois tem os modelos que deseja.

**Comment by simas0** [comment]
Oi Francisco! Acho que foi a Estela ou a Ana que sugeriram este trecho do texto. Mas combinamos terça que a Lição 1 foi para revisão da Estela e ninguém mais deve mexer lá. Acredito que ela mesmo vai descrever a figura. Vou mudar a atribuição para lembrá-la disso. Abraço!

**Comment by simas0** [comment]
Oi Francisco, a Estela está tendo dificuldades em finalizar a Lição 1. Você poderia ajudá-la com aquelas Conexões? Aquele é o único texto do estudante da Lição 1 e está incerto há bastante tempo. Converse com ela para ver se é isso mesmo que ela precisa para finalizar esta Lição, por favor.

**Comment by simas0** [comment]
Feito!
