### ISSUE TITLE
Falta atividade com material concreto dos discos para a Lição 1

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#10]

**Comment by UmLivroAberto** [comment]
Mudei a prioridade porque estamos próximos da entrega e na Atividade 2 da Lição 4 é feita uma referência a esta atividade.

**Comment by cydara** [comment]
Não tenho opinião porque não sei do quê vocês estão falando... Não consigo propor nada portanto.

**Comment by estelanunes** [comment]
Atividade feita. Exigirá dois ajustes no texto: 
(i) Na lição 1 - ordem das atividades - Ela ficu como atividade 10 e não 12.
(ii) Na lição 4 - não incluí as fracões 1/12. Será necessário alterar o terceiro item da atividade que serefere a esta na lição 4. Recomend 1/9.

**Comment by hjbortol** [comment]
(ii) Já alterei o terceiro item da Atividade da Lição 4 que fazia referência a esta atividade.

**Comment by estelanunes** [comment]
👍

Em 25/08/2016 13:23, "hjbortol" <notifications@github.com> escreveu:
