### ISSUE TITLE
Atividade 10 sem referência a uma das figuras 

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#101]
https://www.umlivroaberto.com/livro/doku.php?id=cap1:texto#ativ_comparacao4

Nesta atividade o enunciado global apenas faz referência à figura com reta em vermelho. No item c) espera-se que o estudante use a reta azul, mas nada é dito ao estudante sobre isso.

**Comment by estelanunes** [comment]
Corrigido.
