### ISSUE TITLE
Lição 3 ativ_grad_unidade 3 ainda vai ser feita?

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#104]
https://www.umlivroaberto.com/livro/doku.php?id=cap3:texto#ativ_grad_unidade3

Está escrito apenas "ENUNCIADO......"

**Comment by estelanunes** [comment]
Completei.

**Comment by simas0** [comment]
Você vai me deixar maluco. Acabou ou tem mais?

**Comment by estelanunes** [comment]
Kkkk

Em 28/08/2016 14:01, "Fabio Simas" <notifications@github.com> escreveu:
