### ISSUE TITLE
Figuras desnecessárias na página para reprodução

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#105]
Temos diversos retângulos nestas páginas. Não seria melhor orientar o professor a fazer junto com os estudantes na sala? Isso deve dar menos trabalho do que ficar tirando cópias.

**Comment by estelanunes** [comment]
Não consegui identificar a página.

**Comment by simas0** [comment]
https://www.umlivroaberto.com/livro/lib/exe/fetch.php?media=cap6_folhas_para_reproducao.pdf

https://www.umlivroaberto.com/livro/doku.php?id=start

**Comment by hjbortol** [comment]
(B), (C) e (D)!

**Comment by estelanunes** [comment]
Fábio, acho que as figuras estão enormes. Não vi figura que pudesseser dispensada. Fazer com que todos os alunos reproduzam figuras iguais é uma tarefa muito difícil para o professor. Toma muito tempo e ode não ser bem feita por todos os alunos. Melhor tirar as cópias e garantir que todos estão igualmente preparados para a atividade.

**Comment by simas0** [comment]
Eu posso reduzir, mas não sei quais nem quanto...

Para a próxima etapa precisamos solicitar que sejam especificados os tamanhos das figuras para página de reprodução.

**Comment by estelanunes** [comment]
Talvez isso possa ficar resolvido seconseguirmos visualizar a versão final do texto de maneira mais afinada com a escrita.

**Comment by simas0** [comment]
Eu fiquei imaginando crianças de 10 anos manipulando os papeis cortados e sempre me pareceu que se as figuras fossem maiores facilitaria. Se quiser envie por aqui mesmo o fator que deseja reescalar cada figura da página para reprodução. Por exemplo, 

"Atividade 2 Lição 3 fator 0.6"
