### ISSUE TITLE
Figura para reprodução não especificada Atividade 4 Lição 4

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#106]
https://www.umlivroaberto.com/livro/doku.php?id=cap4:texto#ativ_reta2_unidade6

**Comment by hjbortol** [comment]
Caros, acrescentei uma imagem, mas não estou certo se é exatamente isto o que se quer. @cydara e @estelanunes poderiam, por favor, confirmar?


![torta-tercos-um-doze-avos](https://cloud.githubusercontent.com/assets/7694624/18034202/0bb08ec6-6d0d-11e6-8f99-436a445fbb9c.jpg)

**Comment by simas0** [comment]
Incluído nas páginas para reprodução.
