### ISSUE TITLE
"10, 11, 12, .." e "não briguem"

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#108]
Caros,

Olhando para o detalhe do detalhe ...

Na história em quadrinhos da Lição 2, sugiro trocar a frase

> Esse negócio não parece estar certo. Os números ficam um ao lado do
> outro, 10, 11, 12, ... e não um embaixo do outro como você mostrou aí!

Por

> Esse negócio não parece estar certo. Os números ficam um ao lado do
> outro, 1, 2, 3, ... e não um embaixo do outro como você mostrou aí!

(Começar de 1 me parece mais natural).

Outra sugestão: trocar

> Professora: Crianças, não briguem, os dois estão certos. Vamos falar disso na lição
> de hoje.

por

> Professora: Crianças, acalmem os ânimos, pois os dois estão certos. Vamos falar disso na lição
> de hoje.

(Achei "brigar" um pouco forte).

**Comment by simas0** [comment]
1. Mudar 10, 11, 12, .... para 1, 2, 3, ... vai retirar o sentido esperado da representação posicional dos números.

2. Boa a sugestão, por mim podemos substituir.

3. Contudo o momento é para corrigir erros, não fazer melhorias pequenas estéticas. A alteração pode ser feita na plataforma, mas não será mais inserida no pdf da entrega.

**Comment by simas0** [comment]
Mudei no pdf a segunda sugestão.

**Comment by estelanunes** [comment]
Concordo com o Fábio.

**Comment by hjbortol** [comment]
(1) Entendi! Que tal então começar de 12? 12, 13, 14 ,... em comparação com 1/2, 1/3, 1/4, ...

**Comment by simas0** [comment]
Incluí a sugestão do Humberto no pdf
