### ISSUE TITLE
Espaço em branco

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#109]
No item (d) da Atividade 

https://www.umlivroaberto.com/livro/doku.php?id=cap2:texto#salgadas

da Lição 2, o ponto de interrogação está colado em torta. No PDF, há um espaço em branco:

![licao-02-atividade-15](https://cloud.githubusercontent.com/assets/7694624/18034064/b78d9d8c-6d09-11e6-8974-6a4d3546cc62.jpg)

**Comment by simas0** [comment]
Obrigado! Corrigido.
