### ISSUE TITLE
Listas dentro de listas

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#11]
Estou com um problema na lista dentro de listas. O primeiro item da segunda lista fica com a numeração errada.  Obrigado!

Este código:
![tela-01](https://cloud.githubusercontent.com/assets/7694624/15097997/5249fc10-1505-11e6-9074-02ee4ce08b43.png)

produz este resultado:
![tela-02](https://cloud.githubusercontent.com/assets/7694624/15097998/551c899e-1505-11e6-90e2-e52a4a6b728e.png)

**Comment by gutosurrex** [comment]
Veja se e

**Comment by gutosurrex** [comment]
Parece um problema com o número de espaços no código.

Veja se o seguinte exemplo responde sua pergunta:
https://www.umlivroaberto.com/livro/doku.php?id=sandbox

**Comment by UmLivroAberto** [comment]
Parece que está resolvido pelo que vejo nas lições 1 e 2.
