### ISSUE TITLE
Parágrafo repetido no Organizando as Ideias da Lição 2

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#110]
https://www.umlivroaberto.com/livro/doku.php?id=cap2:texto#conexoes

Acho que tem dois parágrafos que estão explicando a mesma coisa de forma repetida. Minha sugestão: apagar o trecho marcado em amarelo.

Primeiro trecho:

![trecho-01](https://cloud.githubusercontent.com/assets/7694624/18034262/04a24bf4-6d0f-11e6-8422-aa2c229f33b8.jpg)

Segundo trecho (que proponho que seja removido):

![trecho-02](https://cloud.githubusercontent.com/assets/7694624/18034265/0b0f5e64-6d0f-11e6-86a1-f7b122c144d5.jpg)

@simas0 , @estelanunes , @cydara , o que acham?

**Comment by estelanunes** [comment]
Oi Humberto, concordo que está repetido, mas acho que a segunda parte, que começa com o trecho que destacou em amarelo, resgata o que vem antes para complementar. Em particular acho importante a frase que se inicia por "com mais do que uma torta...".  Por mim, pode ficar como está.

**Comment by hjbortol** [comment]
@estelanunes , ok!
