### ISSUE TITLE
Comando da atividade cap2:texto#atividade_complete

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#112]
https://www.umlivroaberto.com/livro/doku.php?id=cap2:texto#atividade_complete

Caros, notei que esta atividade estava com a tabela, mas sem comando nenhum. Por favor, vejam se concordam com o que o texto que inclui.

**Comment by simas0** [comment]
Me pareceu bom e inofensivo. Incluí de uma vez.

**Comment by estelanunes** [comment]
Por mim, ok.
