### ISSUE TITLE
Aspas no arquivo PDF

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#113]
Fábio, algumas aspas não estão sendo interpretadas corretamente no PDF: eles estão no formato LaTeX e não foram processadas! Veja, por exemplo, os "Refletindo" da Lição 4.

![licao-4-aspas](https://cloud.githubusercontent.com/assets/7694624/18034397/656ee7c8-6d12-11e6-9aa0-c973aa629e5f.jpg)

**Comment by simas0** [comment]
Corrigido. Se encontrar novas, avise.
