### ISSUE TITLE
Espaço antes do ponto e vírgula

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#115]
@simas0 ,  neste refletindo

https://www.umlivroaberto.com/livro/doku.php?id=cap4:texto#dobradura_refletindo

tem espaços entre as frações e os ";":

![ponto-e-virgula](https://cloud.githubusercontent.com/assets/7694624/18034432/1cf53a00-6d13-11e6-9e08-694fe5f36d4f.jpg)

Estes espaços devem ficar mesmo?

**Comment by simas0** [comment]
Obrigado! Corrigido.
