### ISSUE TITLE
Ponto final em outra linha

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#116]
Neste refletindo,

https://www.umlivroaberto.com/livro/doku.php?id=cap4:texto#preencha_fita_refletindo

o ponto final saiu na próxima linha.

![ponto-final](https://cloud.githubusercontent.com/assets/7694624/18034461/01e7d546-6d14-11e6-8b96-bf32e6736ab1.jpg)

**Comment by simas0** [comment]
Corrigido!
