### ISSUE TITLE
Primeiro, segundo, ...

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#118]
No jogo de trilha da Lição 4, primeiro está sendo exibido assim:

![primeiro](https://cloud.githubusercontent.com/assets/7694624/18034497/e63fcf3c-6d14-11e6-9e89-7d64c0b982b4.jpg)

Mas, se não engano, a regra é assim:

$1^{\textrm{\underline{o}}}$

![gif latex](https://cloud.githubusercontent.com/assets/7694624/18034508/188e0dc8-6d15-11e6-8e8c-dcd7755a96c1.gif)

**Comment by simas0** [comment]
Corrigido no pdf
