### ISSUE TITLE
Capa do livro

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#119]
Estou pensando em fazer um rascunho de capa. Nela deve constar o símbolo do IMPA, os nomes dos autores (Letícia, Cydara, Fabio, Humberto, Victor, Wanderley e Wellerson - colocamos a Ana Paula?) , o título do livro (Frações - livro didático para o Ensino Fundamental (4o ao 6o ano)) e uma figura de fundo com as cores da paleta de cores.

Gostaria de sugestões de figuras e da opinião de vocês. Precisamos de mais alguma coisa na capa?

**Comment by hjbortol** [comment]
Ana Paula colaborou bem no início, mas eu não incluiria o seu nome.

Eu não colocaria as séries e deixaria apenas Ensino Fundamental. Volume 1 vai aparecer?

Acho que deveríamos aproveitar alguma figura do livro e que representasse alguma novidade Eu sugiro alguma figura da Lição 3: a figura das caixas d'água ou do problema do tesouro. Se tivéssemos as tirinhas, poderíamos incluir um recorte.

**Comment by simas0** [comment]
Mas não temos nada disso...

**Comment by simas0** [comment]
Primeiro rascunho
[capa.pdf](https://github.com/UmLivroAberto/livro/files/441346/capa.pdf)

Feito com o código 

```
\documentclass[a4paper,10pt]{article}
%\documentclass[a4paper,10pt]{scrartcl}

\usepackage[utf8]{inputenc}
\usepackage{tikz}
\usepackage{anyfontsize}
\definecolor{common}{RGB}   {142,178,197}


\begin{document}
\thispagestyle{empty}
\begin{tikzpicture}[remember picture,overlay]
\fill[gray]  ([yshift=2mm,xshift=-2mm]current page.north west) rectangle ([yshift=-5mm,xshift=2mm]current page.south east);
  [xshift=-1.5cm,yshift=-1.3cm] at (current page.south east)
  \node[xshift=-6cm,yshift=-1cm] at (current page.north east) {\normalsize INSTITUTO NACIONAL DE MATEMÁTICA PURA E APLICADA};
 \node[xshift=7cm,yshift=-7cm] at  (current page.north west) { \fontsize{50pt}{10pt} \selectfont {\bf FRAÇÕES}}; 
 \node[xshift=12cm,yshift=-9cm] at  (current page.north west) { \fontsize{20pt}{10pt} \selectfont  para o Ensino Fundamental - Volume 1};
 \fill[white, xshift=2cm,yshift=-5cm]  (current page.north west) (0,0) rectangle (10,-10);
 
 \node[text width=9cm]  at ([xshift=-6cm , yshift=5cm] current page.south east) { \fontsize{20pt}{30pt} \selectfont \bf Letícia Rangel \\ Cydara Ripoll \\ Fabio Simas \\ Humberto Bortolossi \\ Victor Giraldo  \\  Wanderley Rezende \vspace{.5cm} \\  Wellerson Quintaneiro};
 
  
\end{tikzpicture}%

\end{document}`




```

**Comment by estelanunes** [comment]
Eu substituiria o _no_ por _para_:  "Frações para o Ensino Fundamental". Acho que os nossos nome deveriam vir em ordem alfabética.

**Comment by cydara** [comment]
1) Posso ser chata e pedir que meu nome apareça inteiro? Cydara Cavedon Ripoll
2) Como não estamos abordando multiplicação e divisão, fração de um conjunto discreto, que tal o título ficar na forma "Uma Introdução às Frações no Ensino Fundamental" ?
3) Não sou boa em "decoração", mas me ocorrrem duas ideias: 
- fundo em cores pálidas , mas  "Petit-pois",  cada bolinha aparecendo com uma subdivisão diferente, sugerindo alguma fração;
-  fundo em cores pálidas , mas mostrando aqueles  hexágonos encadeados, sugerindo diferentes unidades, mas sempre a mesma fração, por exemplo, 1/3?

**Comment by simas0** [comment]
@cydara, não sei se era isso o que você esperava dos terços... Espero que goste.

Segue a versão que entregaremos na terça ao Marcelo e ao Cláudio.

[Frações.pdf](https://github.com/UmLivroAberto/livro/files/441686/Fracoes.pdf)
