### ISSUE TITLE
Falta atividade para colocar muitas frações na reta na Lição 3

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#13]
Em quase todas as atividades temos apenas poucas frações na reta (exceção do varal dos números?). Precisamos criar ao menos uma em que o estudante posicione muitas frações na reta.

**Comment by cydara** [comment]
tal atividade já existe, na minha opinião: é a ativ_fracoes_na_reta

**Comment by simas0** [comment]
Podemos fechar, @estelanunes ?

**Comment by estelanunes** [comment]
sim
