### ISSUE TITLE
Incluir no "organizando as ideias" da Lição 1 as frações unitárias até décimos;

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#16]
O ideal seria incluir apenas imagens ilustrativas para não tornar o texto muito chato.

**Comment by cydara** [comment]
Vale a pena incluir nos exemplos o tempo e dizer aqui que um sétimo de uma semana é um dia?

**Comment by cydara** [comment]
- Para um sexto podemos pegar um hexágono:A parte colorida da figura é um sexto da figura. Neste caso, a figura é a unidade.

Para um sétimo: Vale a pena incluir nos exemplos o tempo e dizer aqui que um sétimo de uma semana é um dia?

Para um oitavo: poder-se-ia aproveitar a mesma figura dos quarto e tomar apenas a metade da parte azul (já sugerindo metade de um quarto é um oitavo)

Para um nono: três triângulos emendados como em “VVV”, sendo apenas deles particionado em 3 partes, pintada uma delas.

Para um décimo: uma estrela de cinco pontas cortada em 10 partes iguais

**Comment by hjbortol** [comment]
Eu acho que vale a pena sim incluir nos exemplos o tempo e dizer aqui que um sétimo de uma semana é um dia. Não valeria incluir outros exemplos análogos ao longo das lições? 1 minuto é $\frac{1}{60}$ de hora? 1 cm é  $\frac{1}{100}$ de metro? 1 centavo é $\frac{1}{100}$ de real?

Aliás, fiz uma pesquisa reversa por "fração" no Dicionário Houaiss e encontrei alguns verbetes interessantes:

Ação (Rúbrica: Economia.): cada uma das partes em que se considera dividido o capital de uma sociedade anônima; título ou documento de propriedade, negociável e transmissível, representativo de uma fração desse capital; papel

Bandim (Regionalismo: Índia. Diacronismo: antigo.): fração de terreno concedida a um lavrador, quando das distribuições de terras nas aldeias

Bocado: fração de uma coisa; pedaço, porção Ex.: um b. de cera. 

Compasso (Rúbica: Música.):  divisão da pauta musical em partes iguais, separadas por barras (ditas barras de compasso), cada parte contendo o número de tempos (2, 3 ou 4), indicado pelo numerador de uma fração (fração de compasso) localizada no início da peça musical, após a clave.

Dinar (Rubrica: economia.): fração da unidade monetária do Irã, equivalente a 1/100 do rial.

Facção (Derivação: por extensão de sentido.): fração dissidente de um partido

Gasparinho (Rubrica: ludologia. Regionalismo: Brasil.): a menor fração de um bilhete de loteria; gasparino, décimo

Isto (substantivo masculino): porção muito pequena; fração ínfima (de algo)

Macuta (Rubrica: história da numismática. Regionalismo: Angola.): fração do angolar, instituída em 1928 por Vicente Ferreira e valendo cinco centavos.

Market Share (locução substantiva Rubrica: marketing.): grau de participação de uma empresa no mercado em termos das vendas de um determinado produto; fração do mercado controlada por ela.

Nafta: fração líquida do petróleo que destila entre 100oC e 200°C, us. como matéria-prima na petroquímica.

Retalho: parte de um todo; fração.

Trecho: parte de um todo; fração, segmento.

Vilar (Diacronismo: antigo.): fração de vila rústica medieval.

**Comment by simas0** [comment]
Gostei muito da pesquisa que você fez, Humberto! Eu diria que, especialmente,  na lição 1 seria bom tentarmos apresentar exemplos de situações reais que usem frações como estes que o Humberto conseguiu no dicionário. @cydara

**Comment by estelanunes** [comment]
Humberto, adorei a pesquisa! Mas acho que isso não é novidade... ;)

Acho legal não  perdermos essa pesquisa de vista. No entanto, não tenho clareza de que o melhor espaço para explorá-la seja na seção 1. Nessa seção, o objetivo é construir um significado específico para fração. Temo que a variação possa gerar maior complicação para a maioria das crianças. Mesmo o volcabulário para explicar um desses verbetes já não é trivial para os pequenos.

**Comment by hjbortol** [comment]
@estelanunes, concordo com você. Talvez alguns verbetes poderiam vir no final da Lição 2 como curiosidade ou "Você sabia?" ...  Se der tempo, é claro.  O bom é que se estabelece uma conexão com Português.

**Comment by cydara** [comment]
Concordo com as ponderações. Eu mesma tinha ficado na dúvida sobre a
dificuldade e complicação que a questão poderia gerar, pois estamos
trabalhando com modelos contínuos e um sétimo de uma semana passaria pela
discretização como explicaçao para o cálculo com resposta "um dia".
