### ISSUE TITLE
Atividade 6 da Lição 1 - rever enunciado / forma

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#17]

**Comment by cydara** [comment]
Concordo com o enunciado proposto pelo Humberto, mas eu não utilizaria "unidade", e sim "figura". No entanto, entendo o comentário geral que o aluno deveria ser mais exposto nesta Lição ao termo "Unidade". Se é por isso que ele está optando pelo termo, então concordo!

**Comment by hjbortol** [comment]
Cydara, estava figura anteriormente. Mas, aí, a palavra figura era usada duas vezes com significados diferentes. Na primeira frase, "figura" era usada como referência a "unidade", na segunda, "figura" se refere ao desenho apresentado na primeira sentença.  Poderia substituir, na redação original, a segunda "figura" por desenho mas, como você bem observou, acho interessante fazer menção à unidade. Assim, defendo a proposta de se manter "unidade". @estelanunes?

**Comment by estelanunes** [comment]
Sim, Humberto. Discutimos a alateração por causa do duplo significado da palavra figura na versão anterior.  O que acham de uma tabela para ser completada? Poderíamos evitar a repetição na forma e, talvez, o problema de em questão.

Parte	Fração da figura	Figura
	            Metade	
	            Um quarto	
	            Um terço

**Comment by hjbortol** [comment]
@estelanunes , fiz uma primeira redação usando uma tabela. Por favor, veja se está de acordo: https://www.umlivroaberto.com/livro/doku.php?id=cap1:texto#ativ_recomportodo

**Comment by simas0** [comment]
Eu acho que ficou muito bom com a tabela! Mas tenho uma outra questão de redação: usamos as expressões "metade", "um terço" e "um quarto". Não seria mais adequado usar apenas "metade", "terço" e "quarto" ou usar "uma metade", "um terço" e "um quarto"?

**Comment by cydara** [comment]
"Acho "uma metade" meio estranho. Neste caso, sugeriria "um meio". De resto, achei tudo ótimo!

**Comment by hjbortol** [comment]
Sugestões implementadas!
