### ISSUE TITLE
Incluir na Lição 1 uma tirinha que indique metades não convencionais e não iteressantes na prática

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#18]
Por exemplo, meio bolo cortado na altura.

**Comment by simas0** [comment]
Coloquei no Refletindo após a Atividade 4. Gostaria de incluir também o exemplo do bichinho que entra no barbeiro e pede meia tosa e sai com um lado do corpo inteiramente tosado. Mas não sei a procedência.

**Comment by hjbortol** [comment]
Aqui está o link da meia tosa: https://snag.gy/Y801Fv.jpg
É uma tradução do original aqui: http://joegp.com/halfcut/
