### ISSUE TITLE
Da lição 3 para a 4 "Frações da unidade" passa a ser apenas “frações”. 

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#19]
Falta explicar isso ao professor.

**Comment by hjbortol** [comment]
(1) Esta explicação vai entrar na Lição 3 ou na Lição 4?

(2) Me parece que é apenas na Lição 3 que o termo "fração da unidade" aparece com mais frequência e de forma consistente. Nas Lições 1 e 2, existem trechos onde o termo aparece, mas existem trechos onde fração aparece sozinha: "fração unitária" (não deveria ser "fração unitária da unidade"?), "a fração $\frac{1}{4}$ pode ser obtida por duas dobras de papel", ...

(3) Por que não manter "fração da unidade" nas Lições 4 e 5? Qual seria a explicação para não usar mais "da unidade"?

Um abraço!

**Comment by simas0** [comment]
Oi Humberto, acho que a questão aqui é que na Lição 3 começa a fazer sentido a palavra "fração" como objeto de uma frase, antes ela sempre quantificava uma unidade (era um numeral ou adjetivo numeral) e, por isso, precisava ser acompanhada da expressão "da unidade". 

Eu diria que isso precisa estar claro para o professor no início da Lição 3. Nas lições seguintes, assim como depois do Organizando as Ideias da Lição 3 podemos usar os dois termos dependendo do que se quer dizer.

**Comment by cydara** [comment]
Acho que já existe tal comentário no bilhete ao professor no início da Lição 3 bem como no Organizando as Ideias da Lição 3.
Humberto, para mim havia ficado a ideia de se omitir "da unidade" quando se passava a considerar a reta numérica, momento em que fração, implicitamente, passa a ser tratada como número.

**Comment by hjbortol** [comment]
Na Lição 4, no contexto da reta numérica,  "da unidade" aparece na resposta e no refletindo da Atividade: https://www.umlivroaberto.com/livro/doku.php?id=cap4:texto#reta_numerica (acho que é melhor manter ou trocar "da unidade" por "segmento unitário"). O que acham?

**Comment by cydara** [comment]
Concordo com a troca para "segmento unitário" , talvez colocando na primeira vez em que aparece, entre parênteses: "que está, aqui, servindo como unidade".

**Comment by hjbortol** [comment]
Feito!
