### ISSUE TITLE
Equivalente x igual

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#20]
optamos por igual - No início da conversa com o professor, na lição 4, faz-se uso de equivalentes - REVER

**Comment by hjbortol** [comment]
Na verdade, ficou decidido assim: se a fração se refere a algo físico (bolo, chocolate), que dependa da maneira de se partir, usa-se "frações equivalentes"; se a fração se refere a quantidade ou um número, usa-se igual.

**Comment by simas0** [comment]
Isso! Eu só repassei para cá umas anotações da Estela porque achei que este era o espaço adequado. Mas não sei se ela está sendo notificada quando escrevemos aqui.

**Comment by cydara** [comment]
Já anotei esta convenção, mas não sei se está sugerido isso ao professor em algum bilhete...

**Comment by estelanunes** [comment]
Foi isso mesmo o que ficou decidido.

**Comment by hjbortol** [comment]
@Cydara: eu acrescentei na parte do professor do início da lição um parágrafo colocando nossa escolha. O texto ficou assim:

**Frações equivalentes $\times$ frações iguais:** no texto desta lição, usamos o termo //frações equivalentes// quando as frações estão associadas a divisões de algum objeto físico (bolo, torta, etc.), de forma a poder exprimir assim o fato de que processos de partições diferentes podem gerar quantidades iguais (o **processo** de dividir um bolo ao meio e pegar uma parte é diferente de dividir um bolo em quatro partes iguais e tomar duas, apesar da quantidade de bolo em cada caso ser o mesmo). Usamos o termo //frações iguais// quando estas se referem a números, sem um contexto específico. Não se espera que os alunos sejam, nesta faixa etária, capazes de registrar este tipo de diferença: recomenda-se que //frações equivalentes// e //frações iguais// sejam aceitas como respostas válidas.

**Comment by cydara** [comment]
Acabo de ver o grande bilhete ao professor. Acho que ficou claro.
