### ISSUE TITLE
Lição 2 - ajustes na imagem de abertura

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#201]
Pessoal, por favor, confiram se são realmente essas as alterações que são necessárias na imagem de abertura da Lição 2.

1) Retirar as falas das crianças no último quadrinho. Motivos: @estelanunes : "Para evitar fazer parecer que a mãe foi "mais" eficiente que a escola, retirar a fala sobre exemplos de uso de frações. restringir a historinha à questão de representação."

2) No segundo quadrinho a fala de Miguel deve ser "Mas minha mãe me ensinou frações m casa. Tem o meio, o um terço, o um quarto.... até um décimo."
Não deve haver representação numérica de fração nos balõezinhos de fala, apenas no quadro. Nos balões devem estar expressas por extenso: meio, um terço, um quarto, etc.

3) No terceiro quadrinho, a fala da Alice é: "Esse negócio não parece estar certo. Os números ficam um ao lado do outro: treze, quatorze, quinze.... E não um embaixo do outro como você mostrou aí!"

![image](https://user-images.githubusercontent.com/16407253/78601772-b1321e00-782b-11ea-8d8a-ac97ee3cf76a.png)

**Comment by simas0** [comment]
feito.

**Comment by cydara** [comment]
Eu acho que ficou fluído.
Acho meio forte a palavra "briguem"... Ao ler, não tem-se a impressão de
que os meninos estejam brigando...
E a frase "minha mãe sabe do que está falando" poderia ser trocada para
"Acho que minha mãe tem razão, pois hoje ele me mostrou..."
