### ISSUE TITLE
"Para o professor", "Para o Professor" ou "PARA O PROFESSOR"?

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#21]
Em quase todas as seções está Para o professor, mas agora mudaram na lição 1 para "Para o Professor". Por mim tanto faz, mas precisamos ter uma uniformidade no texto.

**Comment by hjbortol** [comment]
Eu prefiro Professor com "P" maiúsculo, pois mostra o valor que damos à profissão. :) Se existisse uma maneira de aplicar um search/replace global, seria fácil fazer a mudança.

**Comment by simas0** [comment]
Pois é,  me dá nos nervos toda vez que preciso mudar alguma coisa no livro todo. @gutosurrex . :-/

**Comment by simas0** [comment]
Caso aconteça uma decisão coletiva a respeito, vemos como mudar no texto todo. Agora percebo que a grande maioria das lições usa "Para o professor", então vou normalizar todos os demais para este. Caso alguém torne a mexer nisso, por favor, use este padrão. @estelanunes , @hjbortol , @cydara .

**Comment by estelanunes** [comment]
ok
