### ISSUE TITLE
Revisar e aprovar ou não edição feita no Refletindo da Lição 1

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#22]
Incluí a descrição de duas tirinhas de quadrinhos que conversei com a Letícia. Fica logo após a Atividade 4.

**Comment by cydara** [comment]
Aprovado!

**Comment by estelanunes** [comment]
E a imagem da meia tosa? Podia ser só uma imagem, sem necessariamente uam tirinha.

**Comment by cydara** [comment]
...com o título "elegância" e um label "meia tosa".

**Comment by simas0** [comment]
Escrevemos para o Jeff  (dono da tirinha do meia tosa) pedindo permissão para usar a tirinha e ele ainda não respondeu... Tudo que consigo pensar aproveitando a ideia dele me soa como plágio. rs 
Melhor esperar pela resposta dele.
