### ISSUE TITLE
Esta figura dos sanduíches serve ou não serve?

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#23]
Um estudante fez a figura a seguir para a atividade [https://www.umlivroaberto.com/livro/doku.php?id=cap4:texto#sanduiches] da Lição 4. 

@hjbortol , @estelanunes , @cydara , o que vocês me dizem? Fica ou peço para fazer os retângulos?

![sanduiches](https://cloud.githubusercontent.com/assets/16407253/17007346/401ec1ea-4ebe-11e6-8db5-2991351869cc.jpeg)

**Comment by hjbortol** [comment]
Na minha opinião, elas não servem pois, por exemplo, no sanduíche (C), tem uma parte que é menor do que outra (tem uma região curvada na borda, que diminui a quantidade de sanduíche). Acho que é melhor fazer retângulos. O que acham Cydara e Letícia?

**Comment by estelanunes** [comment]
Também vejo problema na figura. A questão é que, na prática, não se alcança, por exmplo, a metade ou a quarta parte do sanduiche. O mesmo vale para o chocolate ou a pizza. No entanto, nas imagens, os contornos das representações desses alimentos são menos irregulares. Será que se o pão for mais "quadradinho" a questão não seria remediada? 

Considerando o objetivo principal da atividade (reconhecer que as frações 1/2 e 2/4 são iguais a partir da observação das representações destas frações em modelos retangulares de área) e se concordarem, sugiro ainda alterar o enunciado da atividade para:

A turma de Rita vai fazer um piquenique. A professora comprou pães para a turma preparar sanduíches. Cada colega preparou e repartiu um sanduíche. Veja como alguns dos colegas repartiram o seu sanduiche:
(a) Nessas repartições, que fração do sanduíche pode representar cada uma das partes em que o sanduíche foi repartido?
(b) Em quais dessas repartições é possível comer metade do sanduíche apenas com as partes em que o sanduíche foi repartido? Justifique sua resposta!
(c) Para cada uma das repartições que você deu como resposta no item (a) , expresse, por meio de frações, a metade do sanduíche.

O que acham?

**Comment by cydara** [comment]
Também acho melhor manter retângulos "caricaturando" os sanduíches, mas sugerindo a aproximação com que estamos tratando o assunto.
