### ISSUE TITLE
Lição 1 - atividade "enfiete txt"

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#25]
A atividade "enfeite txt" da Lição 1 precisa ser revista: se temos 4 estrelas e prendemos uma em cada ponta do cordão, sobram apenas duas estrelas, e portanto basta o cordão ser dividido em TRÊS PARTES iguais. Se queremos dividir o cordão em 4 partes, então devemos ter CINCO estrelas. 

Outra coisa: a ilustração não está clara... O ilustrador provavelmente não vai fazer o que queremos....

**Comment by hjbortol** [comment]
Cydara, a atividade é esta aqui? 

https://www.umlivroaberto.com/livro/doku.php?id=cap1:texto#ativ_enfeite

Acho que os cordões a que se refere o enunciado são aqueles que vão ser "amarrados"  nas estrelas. O que se quer é que as estrelas, quando amarradas em algum lugar (talvez um outro cordão) fiquem todas da mesma altura.

**Comment by cydara** [comment]
Sim, rateada minha ao ler novamente a lição! !!!!!
Em 04/08/2016 05:54, "hjbortol" <notifications@github.com> escreveu:
