### ISSUE TITLE
Lição 1 - atividade ativ_desenhar

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#28]
Que tal sugerir-se ao professor que, depois que cada aluno tenha respondido "a metade do quadrado" a partir de suas dobraduras, que o professor tome metade, quarto e oitavo provenientes de dobraduras diferentes e repita a pergunta ao grupo? 
Por exemplo, tome uma metade proveniente da dobradura pela diagonal com o quarto proveniente da dobradura do tipo "+" e o oitavo proveniente por dobraduras do tipo "-" (fatiamentos horizontais) ? Objetivo: o aluno dar-se conta que ainda continuam metade, quarto e oitavo, mesmo que não possam ser obtido um do outro por dobradura e que continua metade sendo o maior.

**Comment by estelanunes** [comment]
A discussão seguiu na plataforma e foi concluída. Não estava registrado aqui.
