### ISSUE TITLE
A lição 2 tem "variáeis" no texto do aluno

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#31]
No Organizando as ideias aparece para o aluno "... que identifica a fração do tipo 1/b,"

Além disso, está sendo sugerida uma figura que explica a notação a/b.

Acho inadequada esta notação para um aluno de 4o. ano...

**Comment by hjbortol** [comment]
Troquei $\frac{a}{b}$ na imagem por $\frac{n}{d}$. Assim, $n$ lembra numerador e $d$ lembra denominador.
