### ISSUE TITLE
Vai ficar este título para a Lição 3?

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#33]
Vai ficar este título para a Lição 3? Que tal “Retomando a reta Numérica”?

**Comment by hjbortol** [comment]
"Frações e A Reta Numérica"?

**Comment by simas0** [comment]
De volta à reta numérica 

Ou

Fracoes do intervalo unitário  na reta numérica

**Comment by cydara** [comment]
Acho bem adequado "Frações e A Reta Numérica". Não estamos dizendo que frações  estarão na reta numérica (título que um matemático criticaria, sem ler o texto) e também estamos dando o recado do que se vai fazer: abordar a reta numérica.

**Comment by simas0** [comment]
Modifiquei o título da lição para "Frações e a reta numérica". Não coloquei aquele "a" maiúsculo porque vai parecer um erro de digitação.
