### ISSUE TITLE
Na ativ_reta1_unidade6, que tal incluirmos mais um item ?

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#34]
Na ativ_reta1_unidade6, que tal incluirmos mais um item repetindo a figura do item (e), agora com unidade sendo Fatia? (Seria o item (f) )

**Comment by cydara** [comment]
Objetivo da minha sugestao: a título de retomada das Lições anteriores, por exemplo, atividade_tres_setimos_ou_tres_quartos da Lição 2.)

**Comment by estelanunes** [comment]
Combinamos, eu e Cydara, que, se der, faremos uma atividade seguinte a ela em que a unidade varie mas mantenha o mesmo tipo. Por exemplo, uma torta, meia torta, fatia de torta, .... ;)
