### ISSUE TITLE
Término das edições das lições 1 a 4

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#35]
Como disse estou na Noruega sem computador. Acho que compro outro até amanhã. Augusto e eu vamos começar a incluir as figuras geométricas e acertar detalhes para termos os pdfs bonitos para a entrega. Quando podemos considerar finalizadas as edições nessas lições? @gutosurex,  @estelanunes,  @hjbortol,  @cydara

**Comment by cydara** [comment]
Eu já fiz meus comentários às lições 1,2,3 e 4. De minha parte,
finalizei-as. No entanto, para continuar com a Lição 5 preciso falar antes
com a Leticia. Estou achando esta história de "subunidade" completamente
inadequada, desnecessária e desviando a Lição do objetivo maior que são as
operações.

2016-08-04 7:23 GMT-03:00 Fabio Simas <notifications@github.com>:

**Comment by estelanunes** [comment]
Conversamos... vamos olhar a lição 5.
