### ISSUE TITLE
Término das edições das lições 1 a 4

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#36]
Como disse estou na Noruega sem computador. Acho que compro outro até amanhã. Augusto e eu vamos começar a incluir as figuras geométricas e acertar detalhes para termos os pdfs bonitos para a entrega. Quando podemos considerar finalizadas as edições nessas lições? @gutossurex,  @estelanunes,  @hjbortol,  @cydara

**Comment by estelanunes** [comment]
Caros, estou com problemas de ordem prática em casa que estão complicando muito a minha vida. Nada grave em si, mas que bagunçou a minha vida e as minhas "férias". Nos próximos  dias, vou trabalhar no LA todos os dias.  Acredito que concluo até domingo.

**Comment by hjbortol** [comment]
Eu estou no final do semestre. Hoje aplico as provas finalíssimas. Pedi para minhas alunas da graduação (PROAES) resolverem os exercícios, criticarem os enunciados, as respostas e as partes para o professor (mesmo sabendo que algo pode mudar).

**Comment by estelanunes** [comment]
Que Bom, Humberto! Ajuda muito bem vinda. ;)

**Comment by simas0** [comment]
Eu pedi para meus dois alunos ajudarem com as resoluções das atividades das Lições 3 e 5 que estão pendentes. Resta saber se eles poderão atender ao pedido.
