### ISSUE TITLE
ativ_grad_unidade4 da Lição 3 precisa ser atualizada

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#40]
Seu enunciado refere-se a uma atividade que já foi excluída. Faço lá uma proposta de reformulação.

**Comment by simas0** [comment]
Não foi excluída. Está lá a atividade ainda sem resposta, com o "Para o professor" não escondido e com a sua sugestão não analisada veja o link

@estelanunes 
https://www.umlivroaberto.com/livro/doku.php?id=cap3:secoes:ativ_grad_unidade4#discussion__section

**Comment by simas0** [comment]
Segue sem resposta a atividade.

**Comment by estelanunes** [comment]
Esta atividade é remanescente da versão 0 da seção... está na UTI. Ainda não consegui salvar. É uma tarefa delicada.

**Comment by estelanunes** [comment]
FInalizada. Ufa! Seria bom que alguém relesse.
