### ISSUE TITLE
ativ_grad_unidade5 da Lição 3

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#41]
Sugiro que seja antecipada (para antes do Jogo o Varal dos Números) e faço lá uma sugestão de reformulação do enunciado

**Comment by estelanunes** [comment]
Esta atividade é remanescente da versão 0 da seção... está na UTI. Ainda não consegui salvar. É uma tarefa delicada.

**Comment by estelanunes** [comment]
Concluído.
