### ISSUE TITLE
Atividade para ser encaixada na Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#42]
Prezados, 
durante minha n-ésima leitura da Lição 3, ocorreu-me a seguinte atividade, com o objetivo de que o aluno se dê conta que "quarta parte" pode significar quantidades diferentes. 

D. Maria e D.Judite fazem, cada uma, um bolo para a festa junina da escola. Trouxeram-nos  cortados em 10 partes iguais. 
Qual décima parte você escolheria?
Figura: o bolo de D.Judite é o triplo da receita do bolo da D.Maria, de modo que é flagrantemente muito maior do que o bolo de D.Judite.
Ao Professor, o bilhete de promover uma discussão que tenha como fechamento atingir-se o objetivo que "um quarto da unidade" está diretamente ligado à unidade considerada, portanto, pode, afinal, estarem associadas a quantidades diferentes, apesar de representados pelo mesmo ponto na reta numérica.

Minha ideia era propor a discussão após a atividade ativ_ident_terço. Mas a Letícia comentou:
Cydara, gosto da sua sugestão, mas acho prematura para esta lição. Ainda não se espera a comparação, muito menos a partir da variação da unidade e não das frações consideradas.
Objetivo desta atividade: Identificar uma mesma fração unitária (no caso, a terça parte) em representações diversas, ou seja, em representações de unidades não necessariamente congruentes.
Sugiro levarmos a sua sugestão para a seção 4. Veja onde acha melhor encaixá-la.

Comecei então a ler novamente a Lição 4, tendo este objetivo em mente. Logo apó ler o grande Bilhete ao Professor do início da lição, acho que uma tal retomada só caberia em Quebrando a Cuca, antes da abordagem de densidade. Deixo para vocês avaliarem. Menciono que discussão análoga à proposta nesta atividade já foi abordada (ativ_ident_terço da Lição 1 (pelo menos para o professor) , as atividade_pinte e atividade_importância_da_unidade da Lição 2. Na verdade, a atividade que proponho é muito parecida com esta última), mas acho bem importante que ela seja novamente trazida à tona depois da abordagem de frações equivalentes e/ou iguais.

Deixo para vocês avaliarem!

**Comment by hjbortol** [comment]
Cydara,

Em uma primeiríssima versão da Lição 1 havia um quadrinho que procurava tratar desta questão da dependência da unidade:

https://www.umlivroaberto.com/livro/lib/exe/fetch.php?media=cap1:quadrinhos-um-meio-e-igual-a-um-quinto.jpg

Como a dependência da unidade é um fato importante que já é tratado na Lição 2 (como você bem apontou), eu talvez incluiria apenas, na Lição 2, um "Refletindo" para explicitar esta dependência para o aluno (pois a atividade sugerida é bem parecida com a atividade em https://www.umlivroaberto.com/livro/doku.php?id=cap2:texto#atividade_pinte).

@estelanunes ?

Um abraço!

**Comment by cydara** [comment]
Ok, mas acho importante ser reiterado este fato de quando em quando. Além disso, apesar de parecida com a atividade que mencionas, Humberto, perguntar ao aluno que pedaço ele escolheria é "mais próximo" do aluno, e ele com certeza vai pensar na questão "com carinho", hehe!

**Comment by estelanunes** [comment]
Concordo que a discussão é importante. Mas, como já havia comentado, acho a atividade sugerida pela Cydara prematura para esta lição. Ainda não se espera a comparação, muito menos a partir da variação da unidade e não das frações consideradas. 

Sobre a questão da dependência da unidade, concordo que é importante que seja reiterada e acho que isso, na medida do possível, foi feito.
