### ISSUE TITLE
problema_motivador Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#43]
Por que escolheu-se disco e não retângulo? A tirinha poderia continuar com um deles dizendo "Com discos parecem quantidades iguais. Vamos tentar com retângulos" O que acham?
Imagino que , dividindo os retângulos apenas com "|", a decisão vai ser difícil também.

Acho que, com esta complementação, a discussão se torna mais "real"...

**Comment by hjbortol** [comment]
Feito!

Aproveitando: aqui está a comparação de 1/3 e 8/25 usando o applet do GeoGebra, agora com retângulos: http://www.im-uff.mat.br/ula/comparacao-fracao-retangulos.gif
