### ISSUE TITLE
Atividade  preencha da Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#44]
Sobre o comentário (1) do Humberto nas discussões, complementei o bilhete ao professor:
É importante, ao final da atividade, observar para os alunos que uma mesma parte do círculo (a área da região pintada de cinza) está sendo descrita por frações com numeradores e denominadores diferentes (isto é, por frações equivalentes), mas que, não obstante, por expressarem uma mesma quantidade, estas frações são iguais, não apenas porque por sobreposição parecem ser a mesma quantidade, mas porque, como na atividade anterior, se cada terço do círculo for subdividido em 2 e 4 partes iguais, respectivamente, então, de fato, 2/3 = 4/6 e 2/3 = 8/12.

**Comment by cydara** [comment]
Humberto, vais disponibilizar, em algum momento, a preciosidade  http://www.im-uff.mat.br/ula/comparacao-de-fracoes.gif para os alunos, não?

**Comment by hjbortol** [comment]
Ok Cydara! Gostei da complementação do bilhete! Com relação ao applet, pretendo criar uma seção na Introdução do livro apresentando os recursos digitais que podem ser usados, caso o professor e os alunos tenham recursos à disposição!
