### ISSUE TITLE
Sobre o preencha_refletindo da Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#45]
Concordo que. a partir de um certo momento, tenhamos sentido necessidade de inserir "refletindo"´s após uma atividade. (Na verdade, estamos, com isso garantindo certas reflexões com o texto, e não apenas com bilhetes ao professor).

NO ENTANTO, na minha opinião, o texto deste Refletindo está muito acadêmico ainda:
- fala em "setor circular" (diferentemente do enunciado da atividade);
- usa a linguagem simbólica 2×4/12=8/12 (multiplicação de fração por número, tratada aqui pela primeira vez)
- para explicar que a/b=(axc)/(bxc) não faz uso da ideia de que, se tomarmos cada 1/b e subdividirmos em c partes iguais então a/b terá a mesma quantidade que (axc)/(bxc) (e isso não é sobreposição!) Esta foi a ideia que eu quis salientar na atividade anterior do João e do Mario). Acho que se é para explorar só este caso de equivalência (multiplicar em cima e embaixo pelo mesmo número), então esta ideia da subpartição deveria ser o que ampara o argumento.

**Comment by estelanunes** [comment]
Concordo com a Cydara, o texto deste Refletindo está muito acadêmico ainda: - fala em “setor circular". Observei também que usa "fração da área do círculo". Talvez seja melhor usar as expressões "região" ou "parte do círculo", para a área destacada em cinza e, simplesmente, "fração do círculo" no lugar de "fração da área do círculo".

**Comment by estelanunes** [comment]
Fiz uma sugestão. Está na pllataforma. Vejam o que acham.

**Comment by hjbortol** [comment]
@estelanunes , na sua sugestão aparece "1/3 é igual a duas vezes 1/6" e "Logo, 2/3 = 2 x 2/6 = 4/6 = (2 x 2)/(2 x 3)". O aluno ainda não viu multiplicação de um natural por uma fração, não é? Se não me engano, até agora temos usado os termos "justaposição" e "cópias" ...

**Comment by estelanunes** [comment]
Humberto, esta é uma das partes que não alterei.... :/  Ficou como na versão original. Tirei apenas uma frase que vinha em seguida porque achei que complicava mais do que exxplicava.

**Comment by cydara** [comment]
Gostei da alteração da Letícia e concordo que deve ser alterada a outra parte também, Humberto!

**Comment by hjbortol** [comment]
@Letícia: tem razão! Sorry. Tirei outros vezes que apareciam!

@Cydara: fiz as modificações.
