### ISSUE TITLE
Atividade  preencha_fita da Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#46]
Não existe "Atividade 17 da Lição 3"  como diz o enunicado e o bilhete ao professor!
Além disso, não estamos fazendo uso de notação DENTRO da parte

Sugestão: eu tiraria o registro das frações e perguntaria numa coluna a mais (que viria a ser a primeira coluna): Quantas peças como essa cabem no retângulo? 
Assim, é o aluno que vai deduzir que a figura laranja é 1/16 do retângulo e daí seguir respondendo as demais colunas.

**Comment by hjbortol** [comment]
@cydara e @estelanunes, pois é: havia uma atividade 17 da Lição 3, originalmente proposta pelo Francisco, que trabalhava com as barras de Cuisenaire (https://en.wikipedia.org/wiki/Cuisenaire_rods). A atividade preencha_fita tinha parte de sua força justamente no uso de um recurso de material concreto que teria sido trabalhado em uma lição anterior (lá o aluno iria aprender que a figura laranja é 1/16 do retângulo). Se a atividade permanecer, o desafio aumenta, pois será a primeira vez que o aluno irá manipular este tipo de recurso. Por que a "Atividade 17" foi tirada da Lição 3?

O mesmo problema ocorre com a atividade preencha (https://www.umlivroaberto.com/livro/doku.php?id=cap4:texto#preencha). Ela pressupõe que uma atividade com material concreto tenha sido trabalhada na Lição 1, mas esta atividade ainda não entrou lá.

Como vamos proceder? Incluir as atividades nas Lição 1 e 3? Remover as atividades da Lição 4? Não fazer referência e deixar como está? @estelanunes , quais são as ordens?

**Comment by simas0** [comment]
@hjbortol a atividade preencha da Lição 4 tem um refletindo importante. Não podemos retirá-la de lá. @estelanunes, chegou a hora de fazer a atividade dos discos na lição 1. @cydara, pode ajudar?

@hjbortol, ao que me parece a atividade  preencha_fita da Lição 4 pode ser adaptada para não precisar daquela da Lição 3. Melhor fazer isso mesmo que a Atividade "17" volte para a lição 3.

Vamos dar um gás para terminar direito este livro, gente!

**Comment by hjbortol** [comment]
Vou trabalhar nisto agora!

**Comment by hjbortol** [comment]
Feito! Por favor, vejam o que acham:

https://www.umlivroaberto.com/livro/doku.php?id=cap4:texto#preencha_fita

**Comment by estelanunes** [comment]
Perfeito!
