### ISSUE TITLE
atividade  preencha_fita_refletindo da Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#47]
O mesmo comentário do refletindo anterior: o texto está muito acadêmico, muita linguagem simbólica.
Que tal colocar o texto como está como bilhete ao Professor? Agora, com o Refletindo da atividade anterior, espera-se que o professor entenda que o que está escrito aqui é a mesma coisa que estamos  querendo salientar no texto do aluno, no refletindo da atividade anterior.
(Imagino que as Lições 4 e 5 continuem escritas para alunos de quarto ano!)

**Comment by hjbortol** [comment]
Vamos tentar mudar a tempo ... Com relação às Lições 4 e 5 serem idealizadas o Quarto Ano, ainda não discutimos isso ... De qualquer modo, faremos um esforço de simplificar a linguagem.

**Comment by cydara** [comment]
Podemos tentar fazer uso de "n" para numerador e "d" para denominador, como sugerido em outra discussão...

**Comment by hjbortol** [comment]
Feito!
