### ISSUE TITLE
atividade reta_numerica da Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#48]
Acho que o item (c ) é delicado, pois do denominador 12 não se chaga, por multiplicação "em cima e embaixo" pelo mesmo número (natural) em denominador 15. No entanto, o professor não foi alertado para isso. Este fato diz respeito à não validade da recíproca que eu comentei no início desta Lição.

**Comment by hjbortol** [comment]
Cydara, mas se chega fazendo uma subdivisão da primeira reta numérica (basta dividir cada terço em 5 partes iguais). A intenção aqui é que o aluno, por si só, acrescente mais uma reta numérica (cópia da primeira reta numérica) e perceba qual divisão fazer dos terços da primeira reta numérica … A referência é sempre com relação a primeira reta numérica. Vou colocar um aviso para o professor.
