### ISSUE TITLE
 atividade reta_numerica_refletindo da Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#49]
- O que é "os três primeiros intervalos da reta numérica " ???
- novamente está se falando em medida ("subintervalo medindo 1/3)  no lugar simplesmente de "1/3 da unidade" e justaposições de tal fração da unidade. 
- eu mudaria a ordem na escrita: a partir da explicação de que cada parte foi subdividida, tem-se 
4/3=(2×4)/(2×3)=8/6 e não 4/3=8/6=(2×4)/(2×3).

**Comment by estelanunes** [comment]
Caros, fiz uma proposta de alteração. Não é o ideal, eu sei.  Não consegui uma alternativa para substituir as variáveis. Acho essa linguagem algébrica muuuito prematura para o nível de escolaridade. Exige uma abstração que os meninos não têm ainda. Mesmo que entendem o processo, dificilmente vou compreendê-lo como descrito.

**Comment by cydara** [comment]
Concordo com a alteração. Só substituí a ordem das igualdades: de 

$$\dfrac{4}{3} = \dfrac{8}{6} = \dfrac{2 \times 4}{2 \times 3},$$.

para 

$$\dfrac{4}{3} = \dfrac{2 \times 4}{2 \times 3} = \dfrac{8}{6} ,$$.

(e também as demais)
por achar que é nesta ordem que estamos reescrevendo a frase anterior em linguagem simbólica.

**Comment by cydara** [comment]
Tentei assim também contemplar minha obs 

- eu mudaria a ordem na escrita: a partir da explicação de que cada parte foi subdividida, tem-se 4/3=(2×4)/(2×3)=8/6 e não 4/3=8/6=(2×4)/(2×3).

E então apaguei o comentário de lá.

**Comment by hjbortol** [comment]
Letícia e Cydara,

Para tentar ajudar, antes da generalização simbólica, coloquei no refletindo (a exemplo no que foi feito para o refletindo das dobraduras), uma construção do GeoGebra que permite gerar vários exemplos diferentes de como perceber que um mesmo ponto da reta numérica pode ser representado por frações com numeradores e denominadores diferentes:

https://www.geogebra.org/m/Pr3s9vak

![geogebra-reta-numerica-equivalencia](https://cloud.githubusercontent.com/assets/7694624/17683616/e890555c-632a-11e6-8ebd-10e55c7a5fcd.jpg)

Caso haja interesse, esta construção pode ser refinada, por exemplo, com as subdivisões sendo exibidas primeiro sem as frações.

De qualquer maneira, acho que precisamos em algum momento conversar sobre o uso de símbolos (como, quando, em que intensidade), o que vai depender de como estamos pensando em distribuir as lições ao longo das séries.

**Comment by cydara** [comment]
Acho ótimo, Humberto! Mas não consegui localizar isso na Lição 4...

2016-08-15 21:00 GMT-03:00 hjbortol <notifications@github.com>:

**Comment by hjbortol** [comment]
Oi Cydara! Coloquei no Refletindo para o Aluno: 

https://www.umlivroaberto.com/livro/doku.php?id=cap4:texto#reta_numerica_refletindo

**Comment by cydara** [comment]
Agora sim!!!
Legal!
