### ISSUE TITLE
organizando_ideias da Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#50]
organizando_ideias
- Alterei as frases “Ora, na lição anterior você aprendeu a comparar frações com o mesmo denominador. Neste caso, como os denominadores eram iguais, você precisou comparar apenas os numeradores da fração. Mas, Miguel e Alice querem comparar duas frações com denominadores diferentes. ” para “Ora, na lição anterior você aprendeu a comparar frações com o mesmo denominador. Neste caso, como os denominadores eram iguais, você precisou comparar apenas os numeradores da fração. Você também aprendeu a comparar frações com o com mesmo numerador. Neste caso, como os numeradores eram iguais, você precisou comparar apenas os denominadores da fração. Mas, Miguel e Alice querem comparar duas frações com denominadores bem como numeradores diferentes. ”

- Discordo do encaminhamento "Ao observar a lista de frações iguais à fração 13, enunciada acima, você deve ter percebido que os denominadores dessas frações são múltiplos de 3. Do mesmo modo, com relação à lista de frações iguais à fração 825, você deve ter percebido que os denominadores dessas frações são múltiplos de 25. Assim, para efeito de comparação, será necessário encontrar frações iguais às frações dadas que possuem denominadores que sejam, simultaneamente, múltiplos de 3 e de 25. O primeiro número que satisfaz essa condição é o número 75=3×25."

Notem que o "generalização do procedimento não contempla O PRIMEIRO NÚMERO QUE SATISFAZ", e nem precisamos disso, pois antes foi salientado: precisamos apenas de um denominador comum. (Neste exemplo, 75 ter sido o primeiro denominador comum é só decorrência de 3 e 25 serem relativamente primos.)

- E novamente eu saliento que o que estamos explicando fica representado simbolicamente por 

1/3=(25×1)/(25×3)=25/75
e que
8/25=(3×8)/(3×25)=24/75.

e não 

1/3=25/75=(25×1)/(25×3)

- Sou de opinião que a generalização do procedimento, se permanecer no texto do aluno, deve ser explicada com palavras e não calcada em linguagem simbólica.

- E quanto aos questionamentos do Humberto: "A comparação de frações está espalhada ao longo das lições e não há uma sistematização para situações particulares anteriores. Assim: (1) Devemos fazer esta sistematização? (Comparar frações de mesmo denominador, mesmo numerador.) (2) Onde esta sistematização será feita? Lição 3? Nesta Lição 4? Minha sugestão: incluir na Lição 3 e deixar para a Lição 4 o caso geral (numeradores e denominadores diferentes). O que acham?"
Respondo:
(1) e (2) com o texto como está, acho que já o aluno está sendo convidado a relembrar como se faz, desnecessário salientar isso. Se for para sistematizar, então acho que deveria ser a Lição 3.

Concordo que de sistematização na Lição 4 deva ficar apenas a comparação de frações de numeradores e denominadores diferentes. 

Mas acho que o aluno teve oportunidade de TALVEZ passar POR ela apenas uma vez até aqui: na atividade reta_numerica (ver meu comentário lá), o que acho pouco...

**Comment by hjbortol** [comment]
Cydara, implementamos todas as suas sugestões, com exceção da última. Estive conversando com o Wanderley. Podemos fazer mais um exemplo no lugar da sistematização simbólica ou, como a técnica vai ser bem exercitada nas atividades que se seguem, simplesmente retirar esta sistematização simbólica. De qualquer modo, deveríamos em algum momento conversar sobre se e como a notação simbólica deve ser apresentada ao longo das séries. É wishful thinking, mas penso que uma introdução gradual (por exemplo, n para numerador e d para denominador) é benéfica.

**Comment by cydara** [comment]
Acho que a notação "n" e "d" é muito interessante e pode ser bem aceita pelos alunos, pois estaríamos aqui apelando apenas para "abreviações" para os termos (assim, como A para área, l para lado.

**Comment by estelanunes** [comment]
Fico achando que este material parece ter mais vocação para a formação do professor do Ensino Fundamental I do que para ser aplicado diretamente com o aluno desse segmento.

**Comment by hjbortol** [comment]
E para um aluno do Ensino Fundamental II?

**Comment by estelanunes** [comment]
Também. As atividades estão ok, mas a linguagem é difícil.

**Comment by simas0** [comment]
Isso nos diz que a elaboração e a revisão devem estar mais bem afinadas. Para isso precisamos da elaboração direto na plataforma para que a revisão seja imediata e evite estes retornos posteriores. O mesmo ocorreu na lição 5. Era um problema do matdigital que ocorria por usar a plataforma moodle. O que acham? 
1. A elaboração tem que ser para

**Comment by estelanunes** [comment]
Concordo. No entanto, acho que importante também a discussão presencial.

**Comment by hjbortol** [comment]
Agora que estamos no final do piloto, para pensar: a Lição 1 foi feita bem em grupo,  as Lições 2, 3 e 4 foram divididas entre os membros grupos e a Lição 5 foi feita por encomenda. Será que se mantivéssemos o esquema da Lição 1 (tudo feito em grupo), não teríamos gasto o mesmo tempo com um resultado melhor e de mais consenso?

**Comment by simas0** [comment]
Eu estava pensando assim para o Ensino Médio: temos uma equipe de 3 a 5 pessoas para cada um dos 5 eixos. Uma delas é coordenadora do eixo (hoje chamamos de revisora). Em cada eixo as pessoas vão trabalhar juntas em cada lição, mas com tarefas diferentes e reuniões presenciais e semanais (texto para aluno, professor, atividades, atividades eletrônicas e revisão).  Se as lições andarem dentro dos prazos, este time fará o trabalho do eixo sequencial e por inteiro, havendo atraso por parte do integrante A, outra pessoa iniciará a tarefa seguinte a que A está fazendo para não atrasar a equipe.  Esta pessoa pode ser outro membro da equipe, que não esteja atrasado, alguém de outra equipe ou mesmo alguém de fora que possa comparecer e consiga dar conta do recado. 

O que me parece fundamental:
a. As reuniões presenciais semanais de cada equipe.
b. Material elaborado em ambiente que permita acompanhamento em tempo real pelo revisor para evitar surpresas como tivemos na lição 5.
c. Revisor dedicado apenas 'a coordenação (incluindo aí o fechamento de trabalhos de membros de sua equipe) para que o acompanhamento da elaboração seja bastante próximo.

**Comment by simas0** [comment]
Podemos continuar a discussão mesmo com o ISSUE fechado. Ele está fechado porque a discussão acabou.
