### ISSUE TITLE
Atividades sem respostas na Lição 3

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#52]
Algumas das atividades do final da Lição 3 ainda estão sem resposta.

**Comment by estelanunes** [comment]
São atividades remanescentes da versão 0 da seção... estão na UTI. Ainda não consegui salvá-las. É uma tarefa delicada.

**Comment by estelanunes** [comment]
Vou fechar esta discussão.... Já está contemplada em #40 e #41. Ok?
