### ISSUE TITLE
atividade equivalencia_pint na Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#53]
Por que não perguntamos se "é possível", para não sugerir ao aluno que SEMPRE é possível?
Como queremos enunciados no imperativo, sugiro "verifique se é possível completar um número inteiro de níveis do copo de seu irmão de modo a ficar com a mesma quantidade de suco. Em caso afimrativo, explique sua resposta."

**Comment by hjbortol** [comment]
Sugestão implementada!
