### ISSUE TITLE
Puxar para a Lição 3 a atividade equivalencia_menor da Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#54]
Concordo !
De fato, esta atividade nada tem a ver com equivalência de frações, e também nada tem a ver com a discussão do Organizando as ideias desta Lição.
Ela pode ser posicionada em Quebrando a Cuca da Lição 3

**Comment by cydara** [comment]
Daí, não esquecer de alterar a numeração das atividades no bilhete ao professor no início da Liçao!!

**Comment by simas0** [comment]
Isso das referências está muito chato! Vamos fazer o seguinte: vou colocar um tag neste issue para não esquecermos, mas vou tentar colecionar todas as mudanças de posição de atividades para fazermos tudo de uma vez e corrigirmos as referências junto.

**Comment by hjbortol** [comment]
Também acho que a atividade poderia ir para a Lição 3. Por outro lado, como apontou a Letícia, é uma oportunidade de revisitar o assunto. Neste sentido, talvez a atividade pudesse ir para o início da Lição 4.

**Comment by cydara** [comment]
Sugiro então que fique como está (na Lição 4). De fato, Há algo mais aprofundado aqui, que é tratar com o infinito. Acho que pode ser fechada esta discussão.

**Comment by hjbortol** [comment]
Certo. Vou fechar a discussão então.
