### ISSUE TITLE
Atividade comparacao da Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#55]
Faltam as justificativas nas respostas, essenciais aqui porque foi perguntado ao aluno "por que?"

**Comment by cydara** [comment]
refiro-me  aos itens a,b e c.

**Comment by estelanunes** [comment]
A atividade é ótima. No entanto, como as operações ainda não foram tratadas com frações (e claro, não tem relação com operar apenas com os termos), sugiro a seguinte alteração no enunciado:

DE: A fração determinada pela adição de 1 ao numerador da fração 4/7 é maior, menor ou igual a 4/7? Por quê?

PARA: Escreva a fração que tem o numerador igual ao da fração 4/7, mas cujo denominador seja igual a 8? Essa fração é maior, menor ou igual a 4/7? Explique como chegou a essa conclusão.
ou 
Escreva uma fração que tenha o numerador igual ao da fração 4/7, mas cujo denominador seja maior do que 7? A fração que você escreveu é maior, menor ou igual a 4/7? Explique como chegou a essa conclusão.

**Comment by cydara** [comment]
Concordo!

**Comment by hjbortol** [comment]
Todas as sugestões implementadas.
