### ISSUE TITLE
Atividade equivalencia_fracoes_diferentes da Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#57]
Acho que o comentário ao professor "Um resultado que pode ser comentado com os alunos, mas cuja a justificativa foge do escopo do Ensino Fundamental é o seguinte: se duas frações irredutíveis têm numeradores e denominadores diferentes, então elas são diferentes. A prova deste resultado usa o seguinte lema: se bb, cc e dd são números naturais tais que dd divide bcbc e o máximo divisor comum de dd e cc é 1, então dd divide bb (este lema, por sua vez, é consequência do Teorema Fundamental da Aritmética). Sejam abab e cdcd duas frações irredutíveis tais que ab=cdab=cd. Se ab=cdab=cd, então ad=bcad=bc. Logo, dd é divisor de bcbc. Pela lema, dd é divisor de bb, uma vez que o máximo divisor comum de dd e cc é 1. Assim, existe natural kk tal que b=kdb=kd. Portanto, ad=bc⇒akb=bc⇒ak=cad=bc⇒akb=bc⇒ak=c. Assim, ad=bc⇒ad=bka⇒d=bkad=bc⇒ad=bka⇒d=bk. Mas, então, k=1k=1, de modo que a=ca=c e b=d"

pode ser excluído e substituído por

Avalie a discussão sobre a veracidade da afirmação do item (d) quando acrescentamos a informação "uma das frações é irredutível" ou "uma das frações é unitária". Aqui as justificativas são generalizações de questões já propostas.

**Comment by cydara** [comment]
- Continuo achando o comentário ao professor exagerado, portanto inadequado. Ele poderia ser substituído por "Note que o item (d) é falso porque estamos dando a liberdade de a escolha envolver frações que não são irredutíveis nem unitárias, por isso existem contraexemplos. Avalie a discussão sobre a veracidade da afirmação do item (d) quando acrescentamos a informação “uma das frações é irredutível” ou “uma das frações é unitária”. Neste caso, as novas afirmações são verdadeiras, e as justificativas para elas são generalizações de questões já propostas." 
- Acho que uma maneira de "aliviar" para o aluno toda a atividade é substituir "iguais" por "representam a mesma quantidade". Daí, a argumentação na resposta ao item (a) por ser na forma "são representados pelo mesmo ponto na reta, pois 1/2=(3×1)/(3×2)=3/6"

**Comment by hjbortol** [comment]
Cydara:

Com relação a sua primeira observação, concordo. A parte que estava escrita era sobre o item (E) que não existe mais (se duas frações irredutíveis tem numeradores ou denominadores diferentes, então elas são diferentes).

Com relação a segunda observação, existe a questão: pergunto ao aluno se $\frac{1}{2}$ é igual a $\frac{2}{4}$. Ele então justifica usando uma torta. Esta resposta é aceitável?

**Comment by cydara** [comment]
Depende de como ele faz uso da torta:
- se apenas fizer sobreposição, acho que não;
- se ele explicar que subdividiu cada metade em duas partes, e então 1/2 é a mesma quantidade que 2/4 sim. No meu ponto de vista, ele se apoiou no concreto mas argumentou de forma precisa.

**Comment by hjbortol** [comment]
Cydara, neste caso, acho que podemos deixar como está: mesmo que no enunciado esteja "iguais", o aluno pode fazer uso de um modelo ou de uma situação para justificar que são iguais, pois expressam a mesma quantidade.

**Comment by estelanunes** [comment]
Humberto, seria bom excluir o caso do 0 no item (c). O que acha?

**Comment by hjbortol** [comment]
Sim, tem razão! Feito!
