### ISSUE TITLE
atividade equivalencia_densidade_1 da Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#58]
- Quem sabe com um bolo, que, a cada etapa, vai-se cortando a metade do pedaço obtido na última etapa? Do tipo

João levou de lanche para a escola um pedaço de bolo. Na hora do lanche, percebeu que seu colega Mário não havia levado lanche. Deu-lhe, então, metade do seu pedaço. Daí, chega maria e diz que também havia esquecido do lanche em casa. João então, deu a ela metade do pedaço que lhe havia sobrado.

etc

- Além disso, nos ítens (D) e (G) o termo "É possível continuar este processo" está inadequado.

- No bilhete ao professor precisa ser explicado a ele o significado de densidade.

**Comment by simas0** [comment]
Eu gostei muito desta ideia e acho que poderia vir (talvez como uma curiosidade) na Lição 4 e depois novamente na Lição 5 em um refletindo: podemos retomar a historinha do bolo acima e observar que se o processo continuar para sempre a unidade (pedaço de bolo) poderá ser recomposto (ou representado) por metade, mais um quarto, mais um oitavo, mais um dezesseis avos, etc. Assim, embora não faça realmente sentido neste momento uma soma com infinitas parcelas, teríamos a igualdade abaixo nesta situação hipotética (em que os meninos tem vida infinita e conseguem seguir repartindo indefinidamente o bolo)
1 = 1/2 + 1/2² + 1/2³ + ...

Sei que parece absurdo mostrar isso para os estudantes, mas acho que é muito bonita esta possibilidade de discussão neste exemplo concreto.

**Comment by hjbortol** [comment]
Hummm ... Acho complicado associar a divisão sucessiva por 2 a um objeto físico. Afinal, o que acontece quando chegarmos ao nível atômico? Mecânica quântica? A matéria é discreta ou contínua? Talvez o melhor seja deixar a divisão de um objeto matemático abstrato mesmo: um quadrado, um círculo ou um segmento de reta.

**Comment by simas0** [comment]
Eu incluiria ao professor que esta é o tipo de aplicação da matemática que fazemos: trabalhar com modelos abstratos de situações reais. Por isso melhor mudar o _"se o processo continuar para sempre..."_ para _"se for possível continuar o processo para sempre..."_

Eu acho que em matemática deveríamos usar mais estas brincadeiras do tipo _"what if?"_ Porque é exatamente o que fazemos num modelo matemático, desprezamos diversas das condições reais, consideramos algumas hipóteses, 'as vezes pouco razoáveis como pedras bidimensionais ou oceanos infinitos (rs), e obtemos respostas bastante aceitáveis para o mundo real. :)

**Comment by estelanunes** [comment]
Caros, acho a discussão bastante delicada para ser conduzida por um professor das séries iniciais. Não precisaria ser tão aprofundada. Até gosto da ideia do Fábio, mas o texto não pode induzir raciocínios ou conclusões errados... Se optarmos pelo bolo, de fato, não há como prosseguir a divisão do bolo infinitamente. Além disso, não sei se concordo com o termo "para sempre". Eu prefiro a atividade como está. Não está nada fácil e, acho, pouco adequada ao nível escolar. No entanto, não parece encerrar erros. Creio que há apenas a necessidade de excluir o zero como resposta nos itens (a) e (d).

**Comment by cydara** [comment]
Acho a ideia de trocar bolo por círculo ou retângulo boa, mas concordo com a Letícia. Como estã, eu só trocaria o termo "continuar o processo", porque acho que nos ítens (D) e (G) não estamos "continuando o processo" e sim "generalizando": qualquer que seja a fração menor do que 1,, é sempre possível determinar uma outra fração menor do que ela.

**Comment by hjbortol** [comment]
Sugestões da Cydara e da Estela incorporadas!
