### ISSUE TITLE
equivalencia_densidade_refletindo da Lição 4

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#59]
Troquei o início
"Nas atividades 23 e 24 você estudou uma propriedade importante do conjunto das frações: a densidade.

Isto é, dadas duas frações abab e cdcd diferentes (suponha ab<cdab<cd), sempre é possível determinar uma terceira fração pqpq tal que ab<pq<cdab<pq<cd."

por palavras, evitando o nome "densidade" que, para o aluno, não é importante, a meu ver:

"Nas atividades 23 e 24 você estudou uma propriedade importante do conjunto das frações:

dadas quaisquer duas frações que representam diferentes quantidades, sempre é possível encontrar uma  fração entre elas. "

**Comment by simas0** [comment]
Acho que no final deste refletindo deveria vir uma observação do análogo da densidade na reta e uma conclusão geral motivadora. Acho que dar o nome 'densidade' para os alunos, marca um pouco que isto é algo que importante e uma maneira de se referir a esta propriedade.

> "Conclusão: entre duas frações diferentes na reta numérica sempre há uma fração. Mais do que isso, pode-se afirmar que entre dois pontos diferentes da reta numérica (representem frações ou não) sempre há uma fração entre eles, mas isso será visto alguns anos a frente e será chamado de **densidade** do conjunto numérico formado pelas frações."

**Comment by estelanunes** [comment]
Caros,  continuo achando este refletindo com uma linguagem muito difícil para a criança. (Até para o professor!). Não vejo necessidade de nomear a densidade.

**Comment by cydara** [comment]
Também acho mencionar o termo para aluno de 4o. ano muito exagerado!

Fabio, uma coisa é  a densidade do conjunto de frações, e outra é a densidade do conjunto de pontos da reta, que é equivalente à densidade de IR... Acho que, mesmo que este texto estivesse sendo escrito para anos finais do EF, a comparação é perigosa, pois ajuda a acreditar  que na reta não há pontos que não são etiquetados por frações. De qualquer modo, acho ambas as frases inadequadas para 4o.ano.

**Comment by hjbortol** [comment]
Algumas ponderações:

(1) Vale a pena incluir para o aluno que a propriedade de densidade implica que não existe o sucessor de uma fração? Uma propriedade marcante que diferencia IN de Q!

(2) Bem, parece que uma estratégia para substituir a generalização via símbolos é incluir mais exemplos. O que acham?

(3) A definição de densidade das frações como enunciada nos artigos de ensino de frações é diferente da definição que estamos acostumados em Matemática. Será que se, dado um subconjunto X de IR tal que, dados elementos elementos quaisquer diferentes de X, sempre existe um elemento de X entre esses dois elementos, então X é denso em IR no sentido matemático? X = [0, 1] é um contraexemplo para essa sentença. Mas se X contém os inteiros e satisfaz essa propriedade de sempre ter um elemento entre dois elementos diferentes, então X é denso em IR no sentido matemático.

**Comment by cydara** [comment]
Caros,
eu acho que deveríamos manter o público alvo: alunos de 4o.ano. Porque, se
começarmos a aprofundar, fica sugerido ao professor de 4o.ano que ele deve
escolher atividades que ache adequadas, e corremos o sério risco de ele
nivelar por baixo. Se mantermos 4o. ano, estamos dando o recado do quanto
ele deveria aprofundar o assunto.
Assim, acho que os comentários do Humberto não seriam adequados ao presente
texto.
Abs
Cydara

2016-08-15 22:06 GMT-03:00 hjbortol <notifications@github.com>:

**Comment by hjbortol** [comment]
Olá pessoal!

(1) No refletindo atual, a palavra "densidade" não é apresentada para o aluno, como sugerido pela Letícia e pela Cydara.

(2) No projeto, não deu tempo para pensar e discutirmos em como distribuir o conteúdo ao longo das séries.  No Brasil, o costume é iniciar frações praticamente do zero no Ensino Fundamental II. Já nos EUA, o Common Core faz uma distribuição mais equilibrada. Bem, talvez tenhamos que tratar esse assunto na introdução do livro para dizer ao leitor qual é o público-alvo do material. Como havia dito em uma das reuniões, pensar no Ensino Fundamento II me parece uma opção mais segura, principalmente porque não conseguimos nenhum colaborador e nenhum avaliador com experiência no Ensino Fundamental I.

**Comment by cydara** [comment]
Eu acho que até o momento, o material que temos deve ser de conhecimento de
um professor de 4o. ano, Se bem encaminhado, ele é adequado para alunos de
4o. ano. Acho que isto é o relevante. Se todos esses conteúdos fazem parte
dos currículos atuais, é uma outra história. Um professor de 4o. ano pode
se encantar pelo material e seguir com ele adiante do mínimo recomendado,
simplesmente porque os alunos estão acompanhando (e curtindo os contextos!)

Concordo que tudo isso deva ser explicitado na Introdução, Humberto!

2016-08-17 11:54 GMT-03:00 hjbortol <notifications@github.com>:

**Comment by estelanunes** [comment]
Caros, 
continuo achando que esse refletindo está muito difícil para o público.  Acho que o Humberto está certo: "No projeto, não deu tempo para pensar e discutirmos em como distribuir o conteúdo ao longo das séries." Precisamos levar essa aprendizagem para a próxima etapa. ;)

**Comment by simas0** [comment]
Eu diria que a divisão das lições por séries deveria vir na introdução do material porque é uma pergunta que as pessoas vão fazer. Precisamos pensar nisso. Como a lição 4está encerrada para edições vou fechar este ISSUE.
