### ISSUE TITLE
Criar a estrutura (esqueleto) da Lição 3

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#6]

**Comment by simas0** [comment]
A lição 3 não tem movimentação desde 12/04. Ter um roteiro ajudaria muito quem queira colaborar.

**Comment by franciscomattos** [comment]
Não entendi.

2016-04-17 19:11 GMT-03:00 Fabio Simas <notifications@github.com>:

> A lição 3 não tem movimentação desde 12/04. Ter um roteiro ajudaria muito
> quem queira colaborar.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UmLivroAberto/livro/issues/6#issuecomment-211122855>
>



-- 
"Por um mundo onde sejamos socialmente iguais, humanamente diferentes e
totalmente livres."
             Rosa Luxemburgo

**Comment by simas0** [comment]
Precisamos de um roteiro para a Lição 3 assim como fizemos para a Lição 2 porque isso facilita que outros membros da equipe colaborem e evita o "retrabalho" com diferentes concepções de direcionamento para a Lição.

**Comment by franciscomattos** [comment]
Semana passada antes de iniciar  a lição 3 conversei com Leticia para saber
se havia o esqueleto e como não havia decidimos que seria melhor ela
finalizar a lição 1 e eu escrevia baseado nos itens e depois fariamos os
ajustes.
Então vou agora aguardar as diretrizes.


Em 17 de abril de 2016 23:52, Fabio Simas <notifications@github.com>
escreveu:

> Precisamos de um roteiro para a Lição 3 assim como fizemos para a Lição 2
> porque isso facilita que outros membros da equipe colaborem e evita o
> "retrabalho" com diferentes concepções de direcionamento para a Lição.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/UmLivroAberto/livro/issues/6#issuecomment-211164012>
>



-- 
"Por um mundo onde sejamos socialmente iguais, humanamente diferentes e
totalmente livres."
             Rosa Luxemburgo

**Comment by simas0** [comment]
A estrutura foi concluída em 22/04 pela Estela. A entrega da Lição 3 completará 10 dias de atraso em 29/04. @franciscomattos e @estelanunes precisam acelerar a elaboração desta Lição para mantermos o prazo. Vou pedir que o Michel ajude elaborando atividades para esta lição.
