### ISSUE TITLE
Atividade unidade2 da Lição 5 precisa ser reescrita

### ISSUE THREAD

**Issue by cydara** [UmLivroAberto/livro#64]
Bilhete ao professor: “Esta atividade apresenta explicitamente aos alunos a determinação de um denominador comum com base na ideia de subunidade de medida. 
A subunidade já é dada, e sua determinação não é pedida ao aluno, o que voltará a ser objetivo das próximas atividades.”
Acho exagerado introduzir a ideia de “subunidade” para os alunos, e também desnecessário, uma vez que, na Lição 4 já foi tratado o problema de expressar-se quantidades por frações de mesmo denominador. No Organizando as Ideias da Lição 4 tem-se “A ideia é utilizar o que você aprendeu até aqui nesta lição para encontrar frações iguais às frações 1/3 e 8/25 mas que possuem o mesmo denominador.” Após o Organizando as Ideias na Lição 4, tem-se mais de dez atividades explorando isso. Para o aluno, a atividade em questão não precisa de conceitos novos para ser resolvida.
Por isso acho que a atividade precisa ser toda reenunciada (não apaguei nenhum comentário dela porque acho que ainda todos são válidos). 

Como as perguntas são interessantes, já incluí lá as respostas.

**Comment by cydara** [comment]
Leio a atividade seguinte e continuo vendo que a ênfase está em um conceito "novo" e não nas operações com frações. O pior de tudo é tal conceito ser completamente desnecessário para o que se quer.
Para o aluno, quala diferença entre "fração unitária" e "subunidade"?????
Fabio, estou parando de ler a Lição 5. Só vou continuar depois que conseguir falar com a Leticia.

**Comment by estelanunes** [comment]
Cyadara, isso jã foi passado para o Victor e o Wellerson. Eles estão cientes desses problemas. Em particular, há três conceitos cuja diferença não está clara nem a necessidade bem defendida: "Como diferenciar, para a criança, as ideias de unidade comum, subunidade comum e unidade?".

**Comment by cydara** [comment]
Bom, então  eu vou esperar que sejam feitas as alterações antes de continuar lendo a última Lição.

**Comment by simas0** [comment]
A Lição 5 foi atualizada para sua última versão. Pode seguir lendo, @cydara.
