### ISSUE TITLE
Terminologia_liçao4

### ISSUE THREAD

**Issue by estelanunes** [UmLivroAberto/livro#65]
Caros, observei que ao longo da lição 4 aparecem, de formas variadas, expressões como "modelos de área retangulares" ou "modelos de área circulares" .  Acho melhor "modelos retangulares de área" ou "modelos circulares de área". Estou fazendo a substituição, mas queria saber se concordam. O que acham?

**Comment by hjbortol** [comment]
@estelanunes, em Inglês, "Model Area" (Modelo de Área) é uma expressão bem usada. Em Inglês, encontramos também "Rectangular Area Model" (Modelo de Área Retangular) (5000+ hits no Google). Em Português, não encontrei "Modelos de Área Retangulares" e apenas 1 ocorrência de "Modelos Retangulares de Área".

Eu prefiro "Modelos de Área Retangulares", pois existem os "Modelos de Área" no geral, sendo um tipo os retangulares.

**Comment by cydara** [comment]
Bah, não tenho opinião... Será que não está dependendo se "área" está sendo usada como região ou como número? Me abstenho!

**Comment by estelanunes** [comment]
Vamos deixar com a terminologia proposta pelo Humberto.
