### ISSUE TITLE
Varios modelos

### ISSUE THREAD

**Issue by estelanunes** [UmLivroAberto/livro#66]
Proponho a seguinte alteração para o enunciado desta atividade. Humberto e Cydara, se concordarem, faço a alteração nos três itens:

De: 
  - Tomando um círculo como unidade, faça um desenho que represente $\frac{5}{4}$ da unidade e, a partir deste desenho, obtenha uma fração de denominador $12$ que seja igual a $\frac{5}{4}$. 

PARA:
 - Tomando um círculo como unidade: (i) faça um desenho que represente $\frac{5}{4}$ da unidade. (ii) Usando o desenho feito, represente uma fração de denominador $12$ que seja igual a $\frac{5}{4}$.

**Comment by cydara** [comment]
Concordo!

2016-08-08 18:16 GMT-03:00 estelanunes <notifications@github.com>:

**Comment by hjbortol** [comment]
Mudanças efetuadas!
