### ISSUE TITLE
equivalencia encontre_lição 4

### ISSUE THREAD

**Issue by estelanunes** [UmLivroAberto/livro#67]
Cydara, não entendi a sua alteração.

**Comment by cydara** [comment]
É que qualquer fração equivalente a uma fração irredutível só poderá ter seu numerador e seu denominadro múltipo do numerador e do denominador da fração irredutível.

Já o mesmo não acontece com uma fração equivalente a 6/10 (que é não irredutível). Por exemplo, 6/10=3/5=15/25, e 15 e 25 não são múltiplos de 6 e 10, respectivamente. 
Quis salientar para o professor que este exercício é do tipo "fácil". Mais difícil seria pedir uma fração equivalente a 6/10 com denominador igual a 25.

**Comment by estelanunes** [comment]
Mas acho que não foi isso o que você escreveu.... 

"Determinar uma fração igual a uma dada fração com denominador especificado mas ainda uma fração irredutível."

A fração a ser determinada (cujo denominador é especificado) não será irredutível!

**Comment by cydara** [comment]
Bah, acho que tens razão! Ficou mal a escrita... A fração original é que é irredutível, era isso o que eu quis dizer!!!
