### ISSUE TITLE
Lição 2 fechada para edição

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#68]
Não consigo fazer modificações na Lição 2 ... @simas0 e @gutosurrex  ...

**Comment by simas0** [comment]
Eu fechei para acertar o pdf, conforme havia dito. Vou reabrir, mas preciso que termine até 'as 13h as edições. É possível?

**Comment by hjbortol** [comment]
Ok! Já terminei: foram 3 correções.
