### ISSUE TITLE
Escrever texto para estudante e do professor da Lição 2

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#7]

**Comment by simas0** [comment]
Oi @hjbortol, você poderia substituir a Ana nesta lição 2 com o texto para o estudante e para o professor? Se você topar precisamos combinar o número de horas extras da "consultoria adhoc" que você vai gastar para finalizar esta parte.

**Comment by hjbortol** [comment]
Fabio, posso fazer, mas não seria mais salutar ter variedade genética no texto, isto é, sempre ter pelo menos duas pessoas trabalhando em cada lição e, para o texto do aluno, ter prerencialmente um professor da escola básica? @estelanunes e Francisco, o que acham?

**Comment by simas0** [comment]
Oi Humberto, eu também acho que este é o ideal. Mas eu abriria uma exceção para a Lição 2 porque @estelanunes e @franciscomattos estão atrasados com as tarefas deles e você já praticamente concluiu a sua parte da Lição 2.
