### ISSUE TITLE
Justificativa para equivalencia_menor da Lição 4

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#72]
Caros,

Minha aluna observou que estava faltando as justificativas para as respostas da Atividade 6 da Lição 4:

https://www.umlivroaberto.com/livro/doku.php?id=cap4:texto#equivalencia_menor

Escrevi as justificativas. Vocês poderiam, por favor, dar uma olhada?

**Comment by cydara** [comment]
Eu acho que poder-se-ia alertar o aluno que as frações nas respostas das
segunda e terceira colunas não são únicas.

**Comment by hjbortol** [comment]
Desculpe, colei o link errado: a atividade é a 12

https://www.umlivroaberto.com/livro/doku.php?id=cap4:texto#equivalencia_menor

**Comment by estelanunes** [comment]
Visto.  De acordo.
