### ISSUE TITLE
Para o professor no início para a Lição 3

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#73]
Letícia e Cydara, somente agora tive tempo para ler a Lição 3 com cuidado. 

(1) Para o professor no início da Lição: achei esta frase "A expressão reta numérica se refere ao modelo de organização dos números na reta. " meio perdida no parágrafo.

(2) Um micro detalhe, mas registro aqui: que tal trocar $n$ por $d$ para lembrar denominador?

Achei alguns erros de digitação que já corrigi.

**Comment by cydara** [comment]
(2) ótima troca!
(1) Pode ser que um professor não tenha segurança sobre o que venha a ser
reta numérica. Por isso a frase, explicando a expressão que aparece no
primeiro objetivo e no início do parágrafo em curso. Sugiro que ela seja
colocada entre parênteses, e que seja corrigida para "A expressão reta
numérica REFERE-SE ao modelo de organização dos números na reta. "

**Comment by estelanunes** [comment]
Sugestões acatadas.
