### ISSUE TITLE
Atividade 6 (ativ_grad_unidade) da Lição 3

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#75]
https://www.umlivroaberto.com/livro/doku.php?id=cap3:secoes:ativ_grad_unidade#discussion__section

(1) No segundo item para o professor, uma vez que foi explicado o papel de $a$, que tal explicar o papel de $b$?

Associar as frações $\frac{a}{b}$ da unidade a pontos na reta numérica a partir da equipartição da unidade em $b$ partes iguais e da justaposição de $a$ segmentos correspondentes à fração $\frac{1}{b}$ da unidade. 

(2) Em outro item para o professor, sugiro indicar que a justaposição se dá a partir de $0$:

Observe que a marcação de $\frac{3}{4}$ pode se dar pela justaposição a partir de $0$ de "pedaços" da fita correspondentes a $\frac{1}{4}$ da unidade ou, reconhecendo que $\frac{1}{2}$ = $\frac{2}{4}$, pela identificação do ponto médio do "pedaço" de fita de extremos $\frac{1}{2}$ e $1$. 

(3) Olhando a resposta do item (a), não seria melhor incluir no enunciado que se deve levar em consideração as marcações da fita?

a. Considerando-se as marcações já existentes na fita, é possível ambos estarem corretos? Justifique sua resposta.

(4) Corrigi alguns erros de digitação.

**Comment by cydara** [comment]
Concordo com tudo, Humberto!

**Comment by estelanunes** [comment]
Resolvi (1) e (2). Valeu pela (4). No entanto, (3) já rolou uma discussão. Eu concordo com o Humberto, mas antes de alterar, gostaria de ter a opinião do Fábio.

**Comment by estelanunes** [comment]
Alterado o enunciado:
"A professora Julia pediu que os seus alunos, Pedro e Miguel, marcassem 1/2 **na reta numérica traçada em uma fita**, como esta que vocês também receberam:"
