### ISSUE TITLE
Atividade 11 (ativ_varal_dos_numeros) da Lição 3

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#80]
https://www.umlivroaberto.com/livro/doku.php?id=cap3:secoes:ativ_varal_dos_numeros#discussion__section

(1) O "Para o Professor" não está formatado com o padrão usado nas demais lições.

(2) O Item (a) pede: "Descreva a posição em que o número do cartão recebido deve ser posicionado na reta numérica.". Como seria uma tal descrição? Na resposta, está a indicação do desenho do varal com os cartões. Sugestão: deixar apenas o Item (b).

(3) No Item (b) pede-se para o aluno dar uma explicação. Na resposta, a explicação não está incluídas.

**Comment by cydara** [comment]
(1) Podemos aceitar isso, pois nenhuma atividade até o momento tinha sido
um jogo...
(2) Também acho "descrever" uma coisa difícil para o aluno de 4o. ano.
Sugestão"explique como você faria para..." Daí a resposta seria "Por
exemplo,..." Mas então, de fato, fica igual ao ítem (b)! Concordo em
retirar o item (a), Humberto.

**Comment by estelanunes** [comment]
Essa versão do jogo é do Fábio. Sei que ele aterou a atividade inicial. Confesso que não voltei para ver com calma como ficou a versão final. Fábio, pode ajudar? Eu vou ler com calma antes de responder.

**Comment by simas0** [comment]
Oi Estela, eu só mudei as frações que seriam aplicadas porque quando tentei jogar em casa os números acumulavam em alguns intervalos e ficava difícil prosseguir...

**Comment by estelanunes** [comment]
Oi Fábio, achei que havia alterado as orientações também... Vou ver.

**Comment by estelanunes** [comment]
Enunciado e orientações ao Professor ajustadas.
