### ISSUE TITLE
Atividade 13 (ativ_comparacao_fracoes_unitarias_na_reta) da Lição 3

### ISSUE THREAD

**Issue by hjbortol** [UmLivroAberto/livro#81]
https://www.umlivroaberto.com/livro/doku.php?id=cap3:secoes:ativ_comparacao_fracoes_unitarias_na_reta#discussion__section

(1) O item (c) para o professor faz o uso da terminologia "fração unitária" e, se está sugerido, ele vai provavelmente usá-la. É o que queremos?

(2) Não entendi a tabela no enunciado. O que é para colocar em (……..)? É para ligar com setas?

**Comment by cydara** [comment]
também não entendi...

**Comment by estelanunes** [comment]
(1) Retirei o termo fração unitária. 

(2) Inicialmente pensei em ligar as frações às respectivas representações na reta . Mas não sabia fazer a imagem ... rsrsrs... Etão pensei na tabela, completando (....... ) com as letras que aparecem na 1a coluna. Coloquei um item resolvido como exmplo. Será que é suficiente?

**Comment by cydara** [comment]
Acho que sim!

2016-08-17 22:44 GMT-03:00 estelanunes <notifications@github.com>:

**Comment by hjbortol** [comment]
Hummm ... Estou achando ainda um pouco confuso, porque tem duas letras na mesma linha. Poderiam ser duas tabelas? Fiz uma modificação. Por favor, vejam se está de acordo.

**Comment by estelanunes** [comment]
Ficou ótimo, Humberto. ;)
