### ISSUE TITLE
Atividade 2 da Lição 3 - "INSERIR FIGURA" sem descrição no Para o professor

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#83]

**Comment by estelanunes** [comment]
Fãbio,
Ativ 2 - N'ao era para ter inserir figura. Retirado.
Ativ 3 - O inserir figura está na resposta e não no para o professor. A ideia é que, em cada item, a as imagens sejam ligadas aos pontos correspondentes na reta numérica. Será que é essa informação é suficiente?
