### ISSUE TITLE
Figura no Organizando as Ideias da Lição 3 - compasso

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#84]
Na primeira figura diz: "A determinação dos pontos correspondentes ao 2, 3, 4, 5, e assim por diante, devem ser ilustradas pelo uso do compasso, sustentando a justaposição de segmentos congruentes, como nas imagens."

Mas no texto para o estudante nada é dito sobre compasso. Colocar os arcos nas figuras vai gerar confusão. O que vocês acham?

@cydara , @estelanunes , @hjbortol

**Comment by hjbortol** [comment]
Eu acho deixaria como está, explicando o uso do compasso apenas para o professor. Aliás, uma questão correlata: o compasso pode ser usado para marcar os pontos correspondentes a 2, 3, 4, ..., como também para marcar os pontos correspondentes 1/3 e 2/3. e qualquer outra fração. Vamos indicar isto para o professor?

**Comment by simas0** [comment]
A construção das frações com régua e compasso depende de uma explicação mais detalhada, inclusive do que significa "construir com régua e compasso". Eu omitiria este detalhe devido ao risco de complicar as coisas para o professor ou tornar o material pouco preciso matematicamente.

**Comment by simas0** [comment]
Seguem as figuras compiladas de tikz para pdf do Organizando as Ideias da Lição 3. Estão ordenadas. Por favor, confira se era isso o que esperavam nas figuras que não tinham esboço, mas apenas descrição. @estelanunes 
[picture_test.pdf](https://github.com/UmLivroAberto/livro/files/428943/picture_test.pdf)

**Comment by estelanunes** [comment]
As figuras ficaram ótimas. Não há necessidade do compasso.
