### ISSUE TITLE
Figuras com descrições precárias na lição 3

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#85]
Em uma das caixas do Organizando as Ideias está escrito como abaixo. Peço que inclua figura a mão para facilitar o entendimento do que se quer na parte geométrica.

>  FIGURAS ARTÍSTICAS (2) E GEOMÉTRICAS (2), as duas primeiras lado a lado, a reta abaixo e a igualdade abaixo da reta:
> 
> a.    UMA PIZZA PARTIDA EM 3/3,
>  b.  UMA BARRA DE CHOCOLATE PARTIDA EM 3/3,
>  c.  RETA NUMÉRICA DESTACANDO A JUSTAPOSICAO DE TRÊS SEGMENTOS CORRESPONDENTES A 1/3 DA UNIDADE
>  d.  3/3=1
> 

[(https://www.umlivroaberto.com/livro/doku.php?id=cap3:secoes:conexoes)]

**Comment by simas0** [comment]
O mesmo acontece em:

> FIGURA GEOMÉTRICA - INCLUIR RETA COM metades, quintos e décimos destacados

Não está claro para mim o que se pretende exatamente. As figuras devem ser feitas 'a mão pelo elaborador.

**Comment by estelanunes** [comment]
Fábio, 
Veja se é suficiente: 
FIGURAS ARTÍSTICAS (2) E GEOMÉTRICAS (1), as duas primeiras lado a lado, a reta abaixo dessas duas figuras e a igualdade abaixo da reta:
**Figuras artísticas, uma ao lado da outra:**
UMA PIZZA PARTIDA EM 3/3 --> Uma pizza inteira, mas fatiada em três fatias iguais
UMA BARRA DE CHOCOLATE PARTIDA EM 3/3 --> Uma barra de chocolate partida em três pedaçoes iguais
**Figura geométrica:**
RETA NUMÉRICA DESTACANDO A JUSTAPOSICAO DE TRÊS SEGMENTOS CORRESPONDENTES A 1/3
 DA UNIDADE ( a reta é como a do item (c) do arquivo que você enviou com as imagens do organizando as ideias)
**Representação numérica:**
3/3=1

**Comment by estelanunes** [comment]
Fábio, 
Acho que neste caso: "FIGURA GEOMÉTRICA - INCLUIR RETA COM metades, quintos e décimos destacados", a figura ficou boa. Mas, pensando agora, se fosse possível  acrescentar três retas, com meios, quintos e décimos separados (além da que já está lá), acho que ficaria legal. O que acha?

**Comment by simas0** [comment]
Esta última observação que você fez sobre separar os meios, quintos e décimos em três retas separadas está cristalina. Farei as alterações. A anterior não entendi o que deve ser diferente do que eu fiz.

**Comment by estelanunes** [comment]
rsrsrs
Não era para ser diferente. Estou caduca.

**Comment by simas0** [comment]
Veja, por favor, se está como você quer. Se não estiver, reabra o issue e explique como melhorar.  
[picture_test.pdf](https://github.com/UmLivroAberto/livro/files/429150/picture_test.pdf)

**Comment by simas0** [comment]
O código para estas figuras está em:
[https://www.umlivroaberto.com/livro/doku.php?id=figuras:cap3:secoes:conexoes]
:-)
