### ISSUE TITLE
Atividade 17 da Lição 3 (ativ_grad_unidade4) faz referência a atividade inexistente

### ISSUE THREAD

**Issue by simas0** [UmLivroAberto/livro#99]
Nesta atividade está escrito:

>  Observe as faixas pintadas na atividade anterior.
>     a. Corte uma das 3 partes da faixa verde. Que fração representa?

Mas nas atividades anteriores não há faixas pintadas.

**Comment by estelanunes** [comment]
Não revi esta atividade ainda! Ainda está na UTI. Vou fazer isso agora.
